export enum VehicleType {
  // Standard route types
  LIGHT_RAIL,
  METRO,
  TRAIN,
  BUS,
  FERRY,
  CABLE_CAR,
  GONDOLA,
  FUNICULAR,

  TROLLEY_BUS = 11,
  MONORAIL = 12,

  // Extended route types
  // https://developers.google.com/transit/gtfs/reference/extended-route-types

  // RAIL
  GENERIC_RAIL = 100,
  HIGH_SPEED_RAIL,
  LONG_DISTANCE_RAIL,
  INTER_REGIO_RAIL,
  CAR_TRANSPORT_RAIL,
  SLEEPER_RAIL,
  REGIONAL_RAIL,
  TOURIST_RAIL,
  RAIL_SHUTTLE,
  SUBURBAN_RAIL,
  REPLACEMENT_RAIL,
  SPECIAL_RAIL,
  TRUCK_TRANSPORT_RAIL,
  ALL_RAIL,
  CROSS_COUNTRY_RAIL,
  VEHICLE_TRANSPORT_RAIL,
  RACK_AND_PINION_RAIL,
  ADDITIONAL_RAIL,

  // COACH
  GENERIC_COACH = 200,
  INTERNATIONAL_COACH,
  NATIONAL_COACH,
  SHUTTLE_COACH,
  REGIONAL_COACH,
  SPECIAL_COACH,
  SIGHTSEEING_COACH,
  TOURIST_COACH,
  COMMUTER_COACH,
  ALL_COACH,

  // URBAN_RAIL
  GENERIC_URBAN_RAIL = 400,
  METRO_RAIL,
  UNDERGROUND,
  URBAN_RAIL,
  ALL_URBAN_RAIL,
  URBAN_MONORAIL,

  // BUS
  GENERIC_BUS = 700,
  REGIONAL_BUS,
  EXPRESS_BUS,
  STOPPING_BUS,
  LOCAL_BUS,
  NIGHT_BUS,
  POST_BUS,
  SPECIAL_NEEDS_BUS,
  MOBILITY_BUS,
  DISABILITY_BUS,
  SIGHT_SEEING_BUS,
  SHUTTLE_BUS,
  SCHOOL_BUS,
  PUBLIC_SERVICE_BUS,
  RAIL_REPLACEMENT_BUS,
  DEMAND_RESPONSIVE_BUS,
  ALL_BUS,

  // TROLLEY BUS
  GENERIC_TROLLEY_BUS = 800,

  // TRAM
  TRAM = 900,
  CITY_TRAM,
  LOCAL_TRAM,
  REGIONAL_TRAM,
  SIGHTSEEING_TRAM,
  SHUTTLE_TRAM,
  ALL_TRAM,

  WATER_TRANSPORT = 1000,

  AIR = 1100,

  GENERIC_FERRY = 1200,

  AERIALWAY = 1300,

  GENERIC_FUNICULAR = 1400,

  // TAXI
  TAXI = 1500,
  COMMUNAL_TAXI,
  WATER_TAXI,
  RAIL_TAXI,
  BIKE_TAXI,
  LICENSED_TAXI,
  PRIVATE_HIRE_TAXI,
  ALL_TAXI,

  // MISCELLANEOUS
  MISC = 1700,
  HORSE_DRAWN_CARRIAGE = 1702,
}
